# GitHub Action for generating a contribution snake game
name: Generate Snake

# Controls when the action will run
on:
  # Runs automatically at 12 AM UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The sequence of runs in this workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: akshar-1801
          # These are the files that will be generated
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg

      # Pushes the files to a branch called output
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}